# Generated by Django 5.1.1 on 2025-12-01 09:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Проживает'), ('completed', 'Выселен')], default='active', max_length=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='clients.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Проживание',
                'verbose_name_plural': 'Проживания',
                'ordering': ['-check_in'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('client', 'status'), name='unique_active_stay_per_client')],
            },
        ),
    ]
